"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Layout } from "antd";
import { CustomHeader, CustomSider } from '@/components';
import { Content, Footer } from "antd/es/layout/layout";
import React, { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [isBreakPointTrigger, setIsBreakPointTrigger] = useState(false);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>
          <CustomHeader />
          <Layout>
            <CustomSider setIsBreakPointTrigger={setIsBreakPointTrigger} />
            <Content style={{ marginLeft: `${isBreakPointTrigger ? "80px" : "250px"}`, overflow: 'auto' }} className="px-6 py-4 min-h-screen bg-gray-100">
              {children}
            </Content>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
